<div style=" font-size:14px;  ">
	<div style="padding: 10px 0px;">
		<!--
		<h1 style="padding: 0px 15px; margin: 0px; overflow: hidden; height: 48px;">
			<a title="天津外贸综合服务平台用户中心" href="http://$host$/" target="_blank" swaped="true">
			<img style="border-width: 0px; padding: 0px; margin: 0px;" alt="天津外贸综合服务平台用户中心" src="http://$host$/data/images/base/email_logo.png" height="48" width="208"></a>
		</h1>
		-->
		
		<div style="padding: 2px 20px 30px;">
			<p>亲爱的 <span style="color: rgb(196, 0, 0);">$username$</span>,您好！</p>
			<p>请点击下面的链接即可完成激活。</p>
			<p style="overflow: hidden; width: 100%; word-wrap: break-word;"><a title="点击完成找回密码" href="$url$" target="_blank" swaped="true">$url$</a>
			<br><span style="color: rgb(153, 153, 153);">(如果链接无法点击，请将它拷贝到浏览器的地址栏中)</span></p>

			<p>感谢您光临天津外贸综合服务平台用户中心，我们的宗旨：做中国最安全，用户最喜欢，社会责任心最强的外贸综合服务平台！  <br>现在就登录吧!
			<a title="点击登录天津外贸综合服务平台用户中心" href="$host$" target="_blank" swaped="true">$host$</a>
			</p>
			<p style="text-align: right;"><br>天津外贸综合服务平台用户中心 敬启</p>
			<p><br>此为自动发送邮件，请勿直接回复！如您有任何疑问，请点击<a title="点击联系我们" style="color: rgb(15, 136, 221);" href="$host$/news/list?type=contect" target="_blank" >联系我们</a></p>
		</div>
	</div>
</div>