
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSRecvServicePortType", targetNamespace = "http://api.csp.ygjt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSRecvServicePortType {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://api.csp.ygjt.com/")
    @RequestWrapper(localName = "receivebyDecryption", targetNamespace = "http://api.csp.ygjt.com/", className = "client.ReceivebyDecryption")
    @ResponseWrapper(localName = "receivebyDecryptionResponse", targetNamespace = "http://api.csp.ygjt.com/", className = "client.ReceivebyDecryptionResponse")
    public String receivebyDecryption(
        @WebParam(name = "arg0", targetNamespace = "http://api.csp.ygjt.com/")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.csp.ygjt.com/")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://api.csp.ygjt.com/")
    @RequestWrapper(localName = "receive", targetNamespace = "http://api.csp.ygjt.com/", className = "client.Receive")
    @ResponseWrapper(localName = "receiveResponse", targetNamespace = "http://api.csp.ygjt.com/", className = "client.ReceiveResponse")
    public String receive(
        @WebParam(name = "arg0", targetNamespace = "http://api.csp.ygjt.com/")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://api.csp.ygjt.com/")
    @RequestWrapper(localName = "receiveOrder", targetNamespace = "http://api.csp.ygjt.com/", className = "client.ReceiveOrder")
    @ResponseWrapper(localName = "receiveOrderResponse", targetNamespace = "http://api.csp.ygjt.com/", className = "client.ReceiveOrderResponse")
    public String receiveOrder(
        @WebParam(name = "arg0", targetNamespace = "http://api.csp.ygjt.com/")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "http://api.csp.ygjt.com/")
        String arg1);

}
